/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-flabs_class
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FLABS_CLASS_API_H
#define INCLUDED_FLABS_CLASS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_flabs_class_EXPORTS
#define FLABS_CLASS_API __GR_ATTR_EXPORT
#else
#define FLABS_CLASS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FLABS_CLASS_API_H */
